### ISSUE TITLE
有办法自定 messages 的内容吗

### ISSUE THREAD

**Issue by mukiwu** [TarsLab/obsidian-tars#14]
以 openAI 为例子，
请问有办法自定义 messages 这段的内容吗

```
messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Who won the world series in 2020?"},
    {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
    {"role": "user", "content": "Where was it played?"}
  ]
```

我原本写在 override input parameters，但发现他会被过滤掉，不会写进去

**Comment by ae86jack** [comment]
<img width="941" alt="Screenshot 2024-08-21 at 15 26 48" src="https://github.com/user-attachments/assets/a6c462ca-de8d-445b-be4a-70567b5efc6d">

**Comment by ae86jack** [comment]
跟app使用不一样。我们是可以编辑消息内容的，包括修改自动生成的 assistant 消息。

**Comment by mukiwu** [comment]
好的，谢谢你！
