### ISSUE TITLE
希望可以增加本地模型 Ollama 

### ISSUE THREAD

**Issue by pprp** [TarsLab/obsidian-tars#16]
现在有一些本地模型比如gemma 2有足够的能力了，可以考虑添加一下

**Comment by ae86jack** [comment]
好的，我列入开发计划

**Comment by ae86jack** [comment]
<img width="798" alt="Screenshot 2024-09-09 at 16 29 33" src="https://github.com/user-attachments/assets/70519d2e-5674-4af8-9d03-985ae4b0f248">
