### ISSUE TITLE
千帆：显示文本生成成功，但无结果生成

### ISSUE THREAD

**Issue by jiaweigoah** [TarsLab/obsidian-tars#17]
![微信截图_20240827110531](https://github.com/user-attachments/assets/c403e8b5-6bf3-45de-924a-297a133cbdaa)
配置百度千帆，使用的时候显示文本生成成功，但是没有看到结果输出，百度智能云控制台也没有看到有调用
![微信截图_20240827110713](https://github.com/user-attachments/assets/6ef4f54b-2f77-4adb-a545-0dcc770be81e)
API key 和 Secret应该没问题

**Comment by jiaweigoah** [comment]
测试阿里千问max没有问题

**Comment by jiaweigoah** [comment]
千帆产生调用了，但是报错了，报错代码 336006：

- messages数组长度必须为奇数
- message入参列表中，索引为偶数的role的值必须是“user”或者“function”
- message入参列表中，索引为奇数的role的值必须是“assistant”

**Comment by jiaweigoah** [comment]
成功了，原因是我在Qwen的回答后面直接调用了QianFan，把Qwen的回答和标签删除后可以正常调用QianFan了。
不过能不能实现同一个Prompt，在Qwen回答完之后，直接调用QianFan，用来进行模型对比与思维拓展呢？新建对话当然是一种形式了，直接用的话可能更简单些。

**Comment by ae86jack** [comment]
我需要模型对比，是新建一个文件，复制过去，然后修改下标签。

**Comment by ae86jack** [comment]
<img width="814" alt="Screenshot 2024-08-27 at 18 24 43" src="https://github.com/user-attachments/assets/2a408d3a-cffa-4eb7-8c11-9919e53ded86">

**Comment by ae86jack** [comment]
<img width="581" alt="Screenshot 2024-08-27 at 18 26 29" src="https://github.com/user-attachments/assets/ca32274b-bf6b-491a-b315-f58b11e35d2f">

**Comment by ae86jack** [comment]
在同一个Prompt，在Qwen回答完之后，是可以直接调用QianFan的。如上图。
