### ISSUE TITLE
豆包不能用

### ISSUE THREAD

**Issue by lugoing** [TarsLab/obsidian-tars#30]
![image](https://github.com/user-attachments/assets/aa6efc7e-8264-4cc2-a291-12cd20e5c0c8)

![image](https://github.com/user-attachments/assets/b7aae8af-a73b-4b3f-8deb-cb8c6b2b5925)

是我的配置有问题吗？

**Comment by ae86jack** [comment]
可能是你的模型参数不对，到你的豆包api控制台看看。或者在 Obsidian的菜单栏 view -> toggle developer tools, 查看日志，看看详细的报错信息

**Comment by lugoing** [comment]
看了下控制台。没看到啥有用的。
![image](https://github.com/user-attachments/assets/f39e7803-dd60-4b90-9cb9-721b3183cda4)


也申请了key
![image](https://github.com/user-attachments/assets/d129f525-3cc3-422e-9d8a-a83581e71338)


是不是我填写的模型名字有问题？我填写的名字就是"Doubao-pro-32k"
![image](https://github.com/user-attachments/assets/ec94bd4e-913b-45e6-afa1-4a79a8449c93)




> 可能是你的模型参数不对，到你的豆包api控制台看看。或者在 Obsidian的菜单栏 view -> toggle developer tools, 查看日志，看看详细的报错信息

**Comment by ae86jack** [comment]
![Screenshot 2024-11-18 at 17 58 53](https://github.com/user-attachments/assets/a9fef7a8-071e-46f0-afc5-c9e094475766)

**Comment by ae86jack** [comment]
“在线推理” 创建推理接入点，以 ep开头的，填到插件设置的模型（不是Doubao-xx）。

**Comment by lugoing** [comment]
哦哦。怪不得。原来是要这个接入点。。。。 我就说呢 。。。。可以正常使用了。。感谢
