### ISSUE TITLE
[bug]: openai baseURL还是使用不了，提示连接错误

### ISSUE THREAD

**Issue by lgf5090** [TarsLab/obsidian-tars#31]
bug: openai baseURL还是使用不了，提示连接错误

![image](https://github.com/user-attachments/assets/f493f03d-a4b2-47dc-9d35-5ca1f170133e)

**Comment by ae86jack** [comment]
这是中转api吧。看看文档的 baseURL，一般来说兼容open AI的 url 后面会带有 v1, 比如 https://api.openai.com/v1， https://dashscope.aliyuncs.com/compatible-mode/v1
