### ISSUE TITLE
Hope to be able to customize the model name and model URL

### ISSUE THREAD

**Issue by Wooden-Gear** [TarsLab/obsidian-tars#4]
Hope to customize the model name and model URL to be compatible with more models

**Comment by ae86jack** [comment]
0.2.0 新增了豆包，百度千帆，阿里千问。
如果在设置页面的 AI 助手中没有你想要的 model 类型 或 baseUrl，可以在设置中的“覆盖输入参数”进行配置，输入 JSON 格式，例如 `{"model":"你想要的model", "baseURL": "你想要的baseURL"}`。

**Comment by ae86jack** [comment]
在README做了说明
