### ISSUE TITLE
希望增加供应商deepseek

### ISSUE THREAD

**Issue by saltfish121** [TarsLab/obsidian-tars#6]
deepseek提供的api是免费的，希望您在闲暇时间能够增加此供应商，感谢！
![image](https://github.com/user-attachments/assets/28c419db-80f0-4b23-b4bc-b79b1d056cc4)

**Comment by ae86jack** [comment]
新版本0.2.1新增了deepseek

**Comment by saltfish121** [comment]
感谢您！！！
