### ISSUE TITLE
能否加入Claude模型？

### ISSUE THREAD

**Issue by yiliqi78** [TarsLab/obsidian-tars#9]
如题，kimi已调试成功，目前重度使用Claude模型，能否加入该模型？

**Comment by ae86jack** [comment]
我周末看看

**Comment by ae86jack** [comment]
@yiliqi78 我在开通账户获取api key遇到困难。能否麻烦你给我一个api key，只用来开发测试，开发完成后再通知你把这个 api key 删掉。发到我的邮箱 ae86jack@gmail.com
